# CPU-only switch (uncomment to build without GPU support).
# CPU_ONLY := 1

# cuDNN acceleration switch (uncomment to build with cuDNN).
USE_CUDNN := 1

# CUDA directory contains bin/ and lib/ directories that we need.
CUDA_DIR := /usr/local/cuda

# BLAS choice:
# atlas for ATLAS (default)
# mkl for MKL
# open for OpenBlas
BLAS := open

# build directory
BUILD_DIR := build

# Uncomment for debugging.
# DEBUG := 1

# enable pretty build (comment to see full commands)
Q ?= @

